class ValidationException(Exception):
    pass

class TestErrorException(Exception):
    pass